# Generated by Django 4.1 on 2025-06-16 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LabourReport', '0012_alter_area_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AreaName', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='WorkArea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LabourReport.workarea'),
        ),
    ]
