# Generated by Django 4.0.6 on 2023-05-10 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LabourReport', '0012_alter_area_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliday',
            name='StructureName',
        ),
        migrations.RemoveField(
            model_name='slinight',
            name='StructureName',
        ),
    ]
