# Generated by Django 4.2.1 on 2023-06-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LabourReport", "0013_remove_sliday_structurename_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RFI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("RFI_Month", models.DateField(null=True)),
                ("RFI_Name", models.CharField(max_length=200, null=True)),
                ("RFI_Number", models.IntegerField(null=True)),
                (
                    "RFI_Image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
            ],
        ),
    ]
