# Generated by Django 4.2.1 on 2023-06-08 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LabourReport", "0014_rfi"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RFI",
        ),
    ]
