# Generated by Django 4.2.1 on 2023-06-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LabourReport", "0015_delete_rfi"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report_Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Area", models.CharField(max_length=200, null=True)),
                ("Date", models.DateField(null=True)),
                ("Status_Day", models.BooleanField(default=False)),
                ("Status_Night", models.BooleanField(default=False)),
            ],
        ),
    ]
