# Generated by Django 4.1 on 2025-06-21 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LabourReport', '0016_report_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report_Status',
        ),
        migrations.AddField(
            model_name='sliday',
            name='StructureName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LabourReport.structure'),
        ),
        migrations.AddField(
            model_name='slinight',
            name='StructureName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LabourReport.structure'),
        ),
    ]
