# Generated by Django 4.1 on 2025-06-21 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LabourReport', '0018_report_status_remove_sliday_structurename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkAreaName', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='area',
            name='AreaName',
            field=models.ForeignKey(default='None', null=True, on_delete=django.db.models.deletion.CASCADE, to='LabourReport.workarea'),
        ),
    ]
