# Generated by Django 4.1 on 2025-06-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabourReport', '0019_workarea_alter_area_areaname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='AreaName',
            field=models.CharField(choices=[('', 'None'), ('Bhopal', 'Bhopal'), ('SBN', 'SBN'), ('KV', 'KV'), ('DBM', 'DBM'), ('MPZ', 'MPZ'), ('RKP', 'RKP'), ('HBM', 'HBM'), ('ALK', 'ALK'), ('AIIMS', 'AIIMS'), ('Bangalore', 'Bangalore'), ('Casting Yard', 'Casting Yard'), ('Casting Yard QC', 'Casting Yard QC'), ('Casting Yard PM', 'Casting Yard PM')], default='None', max_length=200, null=True),
        ),
    ]
