# Generated by Django 4.1 on 2025-06-21 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LabourReport', '0020_alter_area_areaname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='AreaName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LabourReport.workarea'),
        ),
    ]
